name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test --no-restore -v normal

    - name: Build Binaries
      shell: bash
      run: |
          release_prefix="DotNetCoreSandBox-CI-"
          common_args="--no-restore -v normal -c release

          # Build Common Plugins
          dotnet publish DotNetCoreSandBox.Plugins.Core.Common $common_args -o "plugins/DotNetCoreSandBox.Plugins.Core.Common"

          # Build Cross-Platform
          release_name="$release_prefix-cross-platform"
          dotnet publish DotNetCoreSandBox.Server $common_args -o "$release_name/DotNetCoreSandBox.Server"
          dotnet publish DotNetCoreSandBox.Target $common_args -o "$release_name/DotNetCoreSandBox.Target"
          cp -r "plugins" "$release_name/DotNetCoreSandBox.Server"
          cp -r "plugins" "$release_name/DotNetCoreSandBox.Target"

          # Build Windows
          rid=win-x64
          release_name="$release_prefix-$rid"
          dotnet publish DotNetCoreSandBox.Server --no-restore --verbosity normal -c Release -r rid -o "$release_name/DotNetCoreSandBox.Server"
          dotnet publish DotNetCoreSandBox.Target --no-restore --verbosity normal -c Release -r rid -o "$release_name/DotNetCoreSandBox.Target"
          dotnet publish DotNetCoreSandBox.Plugins.Core.Windows $common_args -o "$release_name/DotNetCoreSandBox.Server/plugins/plugins/DotNetCoreSandBox.Plugins.Core.Windows"
          cp -r "plugins" "$release_name/DotNetCoreSandBox.Server"
          cp -r "plugins" "$release_name/DotNetCoreSandBox.Target"
          cp -r "$release_name/DotNetCoreSandBox.Server/plugins/plugins/DotNetCoreSandBox.Plugins.Core.Windows" "$release_name/DotNetCoreSandBox.Target/plugins"

          # Build macOS
          rid=osx-x64
          release_name="$release_prefix-$rid"
          dotnet publish DotNetCoreSandBox.Server --no-restore --verbosity normal -c Release -r rid -o "$release_name/DotNetCoreSandBox.Server"
          dotnet publish DotNetCoreSandBox.Target --no-restore --verbosity normal -c Release -r rid -o "$release_name/DotNetCoreSandBox.Target"
          cp -r "plugins" "$release_name/DotNetCoreSandBox.Server"
          cp -r "plugins" "$release_name/DotNetCoreSandBox.Target"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi
          # Delete output directory
          rm -r "$release_name"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DotNetCoreSandBox-CI-${{ matrix.target }}
        path: DotNetCoreSandBox-CI-*