name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Build Binaries
      shell: bash
      run: |
          release_name="DotNetCoreSandBox-CI-${{ matrix.target }}"
          # Build everything
          dotnet publish DotNetCoreSandBox.Server --framework netcoreapp3.1 --runtime "${{ matrix.target }}" -c Release -o "$release_name/DotNetCoreSandBox.Server"
          dotnet publish DotNetCoreSandBox.Target --framework netcoreapp3.1 --runtime "${{ matrix.target }}" -c Release -o "$release_name/DotNetCoreSandBox.Target"
          dotnet publish DotNetCoreSandBox.Plugins.Core.Common --framework netcoreapp3.1 --runtime "${{ matrix.target }}" -c Release -o "$release_name/DotNetCoreSandBox.Server/plugins/DotNetCoreSandBox.Plugins.Core.Common"
          cp -r "$release_name/DotNetCoreSandBox.Server/plugins" "$release_name/DotNetCoreSandBox.Target"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi
          # Delete output directory
          rm -r "$release_name"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DotNetCoreSandBox-CI-${{ matrix.target }}
        path: DotNetCoreSandBox-CI-*