name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test --no-restore -v normal

    - name: Build Binaries
      shell: bash
      run: |
        release_prefix="bin/DotNetCoreSandBox-CI"
        plugin_path="bin/plugins"
        common_args="-v m -c release --framework netcoreapp3.1"
        platform_args="-p:PublishSingleFile=true --self-contained true"

        # Build Plugins
        dotnet publish DotNetCoreSandBox.Plugins.Core.Common $common_args -o "$plugin_path/DotNetCoreSandBox.Plugins.Core.Common"
        dotnet publish DotNetCoreSandBox.Plugins.Core.Windows $common_args -o "$plugin_path/DotNetCoreSandBox.Plugins.Core.Windows"

        # Build Cross-Platform
        release_name="$release_prefix-cross-platform"
        dotnet publish DotNetCoreSandBox.Server $common_args -o "$release_name/DotNetCoreSandBox.Server"
        dotnet publish DotNetCoreSandBox.Target $common_args -o "$release_name/DotNetCoreSandBox.Target"
        cp -r "$plugin_path" "$release_name/DotNetCoreSandBox.Server/plugins"
        cp -r "$plugin_path" "$release_name/DotNetCoreSandBox.Target/plugins"

        # Build Linux
        rid=linux-x64
        release_name="$release_prefix-$rid"
        dotnet publish DotNetCoreSandBox.Server $common_args -r $rid $platform_args -o "$release_name/DotNetCoreSandBox.Server"
        dotnet publish DotNetCoreSandBox.Target $common_args -r $rid $platform_args -o "$release_name/DotNetCoreSandBox.Target"
        mkdir -p "$release_name/DotNetCoreSandBox.Server/plugins/DotNetCoreSandBox.Plugins.Core.Common"
        cp -r "$plugin_path/DotNetCoreSandBox.Plugins.Core.Common" "$release_name/DotNetCoreSandBox.Server/plugins/DotNetCoreSandBox.Plugins.Core.Common"
        mkdir -p "$release_name/DotNetCoreSandBox.Target/plugins/DotNetCoreSandBox.Plugins.Core.Common"
        cp -r "$plugin_path/DotNetCoreSandBox.Plugins.Core.Common" "$release_name/DotNetCoreSandBox.Target/plugins/DotNetCoreSandBox.Plugins.Core.Common"

        # Build macOS
        rid=osx-x64
        release_name="$release_prefix-$rid"
        dotnet publish DotNetCoreSandBox.Server $common_args -r $rid $platform_args -o "$release_name/DotNetCoreSandBox.Server"
        dotnet publish DotNetCoreSandBox.Target $common_args -r $rid $platform_args -o "$release_name/DotNetCoreSandBox.Target"
        mkdir -p "$release_name/DotNetCoreSandBox.Server/plugins/DotNetCoreSandBox.Plugins.Core.Common"
        cp -r "$plugin_path/DotNetCoreSandBox.Plugins.Core.Common" "$release_name/DotNetCoreSandBox.Server/plugins/DotNetCoreSandBox.Plugins.Core.Common"
        mkdir -p "$release_name/DotNetCoreSandBox.Target/plugins/DotNetCoreSandBox.Plugins.Core.Common"
        cp -r "$plugin_path/DotNetCoreSandBox.Plugins.Core.Common" "$release_name/DotNetCoreSandBox.Target/plugins/DotNetCoreSandBox.Plugins.Core.Common"

        # Build Windows
        rid=win-x64
        release_name="$release_prefix-$rid"
        dotnet publish DotNetCoreSandBox.Server $common_args -r $rid $platform_args -o "$release_name/DotNetCoreSandBox.Server/"
        dotnet publish DotNetCoreSandBox.Target $common_args -r $rid $platform_args -o "$release_name/DotNetCoreSandBox.Target"
        cp -r "$plugin_path" "$release_name/DotNetCoreSandBox.Server/plugins"
        cp -r "$plugin_path" "$release_name/DotNetCoreSandBox.Target/plugins"

    - name: Upload Artifacts (Cross-Platform)
      uses: actions/upload-artifact@v2
      with:
        name: DotNetCoreSandBox-CI-cross-platform
        path: bin/DotNetCoreSandBox-CI-cross-platform/**
    - name: Upload Artifacts (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: DotNetCoreSandBox-CI-linux-x64
        path: bin/DotNetCoreSandBox-CI-linux-x64/**
    - name: Upload Artifacts (macOS)
      uses: actions/upload-artifact@v2
      with:
        name: DotNetCoreSandBox-CI-osx-x64
        path: bin/DotNetCoreSandBox-CI-osx-x64/**
    - name: Upload Artifacts (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: DotNetCoreSandBox-CI-win-x64
        path: bin/DotNetCoreSandBox-CI-win-x64/**