name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test --no-restore -v normal

    - name: Build Binaries
      shell: bash
      run: build.sh -m CI

    - name: Upload Artifacts (Cross-Platform)
      uses: actions/upload-artifact@v2
      with:
        name: DotNetCoreSandBox-CI-cross-platform
        path: bin/DotNetCoreSandBox-CI-cross-platform/**